language: node_js
node_js:
  - "12"
sudo: false
notifications:
  email:
    recipients:
      - spond@temple.edu
      - jwertheim@ucsd.edu
      - steven@stevenweaver.org
    on_success: always
    on_failure: always

branches:
  only:
    - master
    - develop

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - node_modules

script:
  - webpack
  - yarn lint
